/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import javax.swing.JOptionPane;

/**
 *
 * @author MaZZ
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNameTextField = new javax.swing.JTextField();
        LastnameTxTField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ComboName = new javax.swing.JComboBox<>();
        BuyButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PlusButtonAdult = new javax.swing.JButton();
        PlusButtonChilden = new javax.swing.JButton();
        MinusButtonAdult = new javax.swing.JButton();
        MinusButtonChilden = new javax.swing.JButton();
        AmoutAduleLabel = new javax.swing.JLabel();
        AmoutChildenLabel = new javax.swing.JLabel();
        AdultTpyeCheck = new javax.swing.JCheckBox();
        KidsTpyeChack = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setSize(new java.awt.Dimension(40, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 112, -1));
        getContentPane().add(LastnameTxTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 109, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        ComboName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Miss", "Mrs." }));
        ComboName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNameActionPerformed(evt);
            }
        });
        getContentPane().add(ComboName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        BuyButton.setText("Buy");
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BuyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 70, -1));

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("500 bath");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("100 bath");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last-name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Frist-name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        PlusButtonAdult.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        PlusButtonAdult.setText("+");
        PlusButtonAdult.setToolTipText("");
        PlusButtonAdult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonAdultActionPerformed(evt);
            }
        });
        getContentPane().add(PlusButtonAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 35, 30));

        PlusButtonChilden.setText("+");
        PlusButtonChilden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonChildenActionPerformed(evt);
            }
        });
        getContentPane().add(PlusButtonChilden, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 35, 30));

        MinusButtonAdult.setText("-");
        MinusButtonAdult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonAdultActionPerformed(evt);
            }
        });
        getContentPane().add(MinusButtonAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 35, 30));

        MinusButtonChilden.setText("-");
        MinusButtonChilden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonChildenActionPerformed(evt);
            }
        });
        getContentPane().add(MinusButtonChilden, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 35, 30));

        AmoutAduleLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        AmoutAduleLabel.setForeground(new java.awt.Color(255, 255, 255));
        AmoutAduleLabel.setText("0");
        getContentPane().add(AmoutAduleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 20, -1));

        AmoutChildenLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        AmoutChildenLabel.setForeground(new java.awt.Color(255, 255, 255));
        AmoutChildenLabel.setText("0");
        getContentPane().add(AmoutChildenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 20, -1));

        AdultTpyeCheck.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        AdultTpyeCheck.setForeground(new java.awt.Color(255, 255, 255));
        AdultTpyeCheck.setText("Adult");
        AdultTpyeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdultTpyeCheckActionPerformed(evt);
            }
        });
        getContentPane().add(AdultTpyeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 60, -1));

        KidsTpyeChack.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        KidsTpyeChack.setForeground(new java.awt.Color(255, 255, 255));
        KidsTpyeChack.setText("Kids(more than 150)");
        getContentPane().add(KidsTpyeChack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*less than 150 Free");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Zoo Ticket");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 151, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/1083983.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-730, -150, 1280, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int Adult = 0;
    int Kids = 0;
    int priceAdult = 500;
    int priceKids = 100;

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
        // TODO add your handling code here:
        summarize SummarizePage = new summarize();
        if (FirstNameTextField.getText().length() != 0 && LastnameTxTField.getText().length() != 0) {

            if (!AdultTpyeCheck.isSelected() && !KidsTpyeChack.isSelected()) {
                JOptionPane.showMessageDialog(this, "Please Select Tpye");
            }
            if (AdultTpyeCheck.isSelected()) {
                if (Adult == 0) {
                    JOptionPane.showMessageDialog(this, "Please input Amount Adult" );
                }
                if (Adult > 0) {
                    if (KidsTpyeChack.isSelected()) {
                        if (Kids == 0) {
                            JOptionPane.showMessageDialog(this, "Please input Amount Kids");
                        }
                        if (Kids > 0) {
                            SummarizePage.show();
                            dispose();
                        }
                    }
                    if (!KidsTpyeChack.isSelected()) {
                        SummarizePage.show();
                        dispose();
                    }
                }
            }
            if (!AdultTpyeCheck.isSelected()) {
                if (KidsTpyeChack.isSelected()) {
                        if (Kids == 0) {
                            JOptionPane.showMessageDialog(this, "Please input Amount");
                        }
                        if (Kids > 0) {
                            SummarizePage.show();
                            dispose();
                        }
                    }
            }

        }
        if (FirstNameTextField.getText().length() == 0 && LastnameTxTField.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please input your Frist-Name or Last-Name");
        }
        String Fisrt, last;
        SummarizePage.NameLabel.setText(ComboName.getSelectedItem() + " " + FirstNameTextField.getText() + "   " + LastnameTxTField.getText());
        SummarizePage.AmountLabelAdult1.setText(String.valueOf(Adult));
        SummarizePage.AmountLabelKids.setText(String.valueOf(Kids));
        SummarizePage.sumPriceAdultLabel1.setText(String.valueOf(priceAdult * Adult));
        SummarizePage.SumKidsPriceLabel.setText(String.valueOf(priceKids * Kids));
        SummarizePage.sumPriceTotalLabel.setText(String.valueOf((priceAdult * Adult) + (priceKids * Kids)));
        SummarizePage.Adult = Adult;
        SummarizePage.countKids1 = Kids;
        last = LastnameTxTField.getText();
        Fisrt = FirstNameTextField.getText();
        SummarizePage.ComboName = ComboName.getSelectedIndex();
        SummarizePage.Lastname = last;
        SummarizePage.FristName = Fisrt;
        SummarizePage.FullName = ComboName.getSelectedItem() + " " + FirstNameTextField.getText() + "   " + LastnameTxTField.getText();
        SummarizePage.sumPrice = (priceAdult * Adult) + (priceKids * Kids);
        int i = 0, j = 0;
        int cheak = Adult;
        while (cheak >= 4) {
            cheak -= 4;
            i++;
        }
        while (j < i) {
            SummarizePage.sumDiscount += SummarizePage.priceAdult;
            j++;
        }
        SummarizePage.DisPriceLabel.setText(String.valueOf(SummarizePage.sumDiscount));


    }//GEN-LAST:event_BuyButtonActionPerformed

    private void PlusButtonAdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonAdultActionPerformed
        // TODO add your handling code here:
        if (!AdultTpyeCheck.isSelected() && !KidsTpyeChack.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select Tpye");
        }
        if (AdultTpyeCheck.isSelected()) {
            if (Adult >= 0) {
                Adult += 1;
                AmoutAduleLabel.setText(String.valueOf(Adult));
            }
        }
    }//GEN-LAST:event_PlusButtonAdultActionPerformed

    private void MinusButtonAdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonAdultActionPerformed
        // TODO add your handling code here:\
        if (!AdultTpyeCheck.isSelected() && !KidsTpyeChack.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select Tpye");
        }
        if (AdultTpyeCheck.isSelected()) {
            if (Adult > 0) {
                Adult -= 1;
                AmoutAduleLabel.setText(String.valueOf(Adult));
            }

        }


    }//GEN-LAST:event_MinusButtonAdultActionPerformed

    private void PlusButtonChildenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonChildenActionPerformed
        // TODO add your handling code here:
        if (!AdultTpyeCheck.isSelected() && !KidsTpyeChack.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select Tpye");
        }
        if (KidsTpyeChack.isSelected()) {
            if (Kids >= 0) {
                Kids += 1;
                AmoutChildenLabel.setText(String.valueOf(Kids));
            }

        }
    }//GEN-LAST:event_PlusButtonChildenActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void AdultTpyeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdultTpyeCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdultTpyeCheckActionPerformed

    private void MinusButtonChildenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonChildenActionPerformed
        // TODO add your handling code here:
        if (!AdultTpyeCheck.isSelected() && !KidsTpyeChack.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select Tpye");
        }
        if (KidsTpyeChack.isSelected()) {
            if (Kids > 0) {
                Kids -= 1;
                AmoutChildenLabel.setText(String.valueOf(Kids));
            }

        }
    }//GEN-LAST:event_MinusButtonChildenActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ComboNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox AdultTpyeCheck;
    public javax.swing.JLabel AmoutAduleLabel;
    public javax.swing.JLabel AmoutChildenLabel;
    public javax.swing.JButton BuyButton;
    public javax.swing.JButton CancelButton;
    public javax.swing.JComboBox<String> ComboName;
    public javax.swing.JTextField FirstNameTextField;
    public javax.swing.JCheckBox KidsTpyeChack;
    public javax.swing.JTextField LastnameTxTField;
    public javax.swing.JButton MinusButtonAdult;
    public javax.swing.JButton MinusButtonChilden;
    public javax.swing.JButton PlusButtonAdult;
    public javax.swing.JButton PlusButtonChilden;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
